In [1]:
import numpy as np

In [2]:
def plusMinus(arr):
    # Write your code here
    n = len(arr)
    
    if [(-100 <= i <= 100) for i in arr] and (0 < len(arr) <= 100):
        positive_values = [i for i in arr if i > 0]
        number_positive_values = len(positive_values)
        postive_ratio = number_positive_values / n
        postive_ratio = '{:.6f}'.format(postive_ratio)
        
        negative_values = [i for i in arr if i < 0]
        number_negative_values = len(negative_values)
        negative_ratio = number_negative_values / n
        negative_ratio = '\n{:.6f}'.format(negative_ratio)
        
        zero_values = [i for i in arr if i == 0]
        number_zero_values = len(zero_values)
        zero_ratio = number_zero_values / n
        zero_ratio = '\n{:.6f}'.format(zero_ratio)
    else:
        raise ValueError('The size of the array is outside the the range 0 < n <= 100')
        
    print(postive_ratio, negative_ratio, zero_ratio)

In [3]:
arr = np.array(np.random.normal(0, 1, 100))

In [4]:
plusMinus(arr)

0.450000 
0.550000 
0.000000


# Question 2

In [5]:
def miniMaxSum(arr):
    # Write your code here
    if [(1 <= i <= 10**9) for i in arr]:
        sum_ = []
        if arr.count(arr[0]) == len(arr):
            print( 4*len(arr), 4*len(arr) )
        else:
            for i in range(len(arr)):
                sum_.append(sum([val for val in arr if not arr[i] == val]))
            min_value = min(sum_)
            max_value = max(sum_)
            print(min_value, max_value)
    else:
        raise ValueError('An array value is off the constraint--> 1 <= arr[i] <= 10^9')

In [6]:
miniMaxSum([1,2,3,4,5])

10 14


In [7]:
a = [5,5,5,5,5]

# Question 3

In [8]:
def timeConversion(s):
    # Write your code here
    hour = int(s[:2])
    
    if (hour == 12) and s.endswith('AM'):
        hour  = '00'
        return (hour + s[2:8])
    
    elif (hour != 12) and s.endswith('AM') :
        hour = s[:2]
        return (hour + s[2:8])

    elif (hour != 12) and s.endswith('PM'):
        hour = str(int(s[:2]) + 12)
        return (hour + s[2:8])
    
    elif (hour == 12) and s.endswith('PM'):
        hour = s[:2]
        return (hour + s[2:8])

In [9]:
s = '12:01:00PM'

s2 = '12:05:45PM'

In [10]:
timeConversion(s2)

'12:05:45'

In [11]:
def fizzBuzz(n):
    # Write your code here
    for i in range(1, n+1):
        if i % 3 == 0 and i % 5 == 0:
            print('FizzBuzz')
        elif i % 3 ==0 and i%5 != 0:
            print('Fizz')
        elif i % 5 ==0 and i%3 != 0:
            print('Buzz')
        elif i % 3 != 0 or i%5 != 0:
            print(i)

In [12]:
fizzBuzz(10)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz


In [13]:
def findMedian(arr):
    # Write your code here
    n = len(arr)
    arr = sorted(arr)
    median =  arr[n//2]
    return median

In [14]:
arr = [0, 3, 4, 1, 5]
findMedian(arr)

3

In [15]:
n_num = [1, 2, 3, 4, 5]
n = len(n_num)
n_num.sort()
  
if n % 2 == 0:
    median1 = n_num[n//2]
    median2 = n_num[n//2 - 1]
    median = (median1 + median2)/2
else:
    median = n_num[n//2]
print("Median is: " + str(median))

Median is: 3


In [16]:
 arr.count(arr[0]) == len(arr)

False

In [17]:
def lonelyinteger(a):
    # Write your code here
    n = len(a)
    if (1 <= n < 100) and n % 2 != 0:
        unique_element = [a[i] for i in range(len(a)) if a.count(a[i]) < 2][0]
        return unique_element
    else:
        raise ValueError('Length of array must be odd and one unique element')

In [18]:
matrix = np.array([ [1, 2, 3],
           [4, 5, 6],
           [9, 8, 9] ])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 9]])

In [19]:
def diagonalDifference(arr):
    # Write your code here
    dim = len(arr)
    right_diag = [arr[i][i] for i in range(dim)]
    left_diag = [arr[i][-(i+1)] for i in range(dim)]

    return abs(sum(right_diag) - sum(left_diag))

In [20]:
diagonalDifference(matrix)

2

In [22]:
arr4 = [1, 1, 3, 2, 1]

In [29]:
np.zeros(len(set(arr)), dtype = 'int')

array([0, 0, 0, 0, 0])

In [37]:
arr

[0, 3, 4, 1, 5]

In [54]:
def countingSort(arr):
    # Write your code here
    results = [0 for _ in range(100)]
    for i in range(len(arr)):
        results[arr[i]] += 1 
    return results

In [56]:
sorting = countingSort(arr)
sorting[:10]

[1, 1, 0, 1, 1, 1, 0, 0, 0, 0]

In [97]:
def ReverseMatrix(arr):
    col_2 = [arr[i][2] for i in range(len(arr))]
    col_2 = [col_2[len(col_2)-i] for i in range(1, len(col_2) + 1) ]
    
    for i in range(len(arr)):
        arr[i][2] = col_2[i]
        
    row_0 = arr[0]
    row_0 = [row_0[len(row_0)-i] for i in range(1, len(row_0) + 1) ]
    
    for i in range(len(arr)):
        arr[0][i] = row_0[i]
        
    return sum(arr[0][:2]) + sum(arr[1][:2])

In [108]:
matrix = [[112, 42, 83, 119], [56, 125, 56, 49], \
[15, 78, 101, 43], [62, 98, 114, 108]]

In [109]:
np.array(matrix)

array([[112,  42,  83, 119],
       [ 56, 125,  56,  49],
       [ 15,  78, 101,  43],
       [ 62,  98, 114, 108]])

In [110]:
ReverseMatrix(matrix)

414

In [111]:
np.array(matrix)

array([[119, 114,  42, 112],
       [ 56, 125, 101,  49],
       [ 15,  78,  56,  43],
       [ 62,  98,  83, 108]])