In [1]:
import numpy as np

In [2]:
def plusMinus(arr):
    # Write your code here
    n = len(arr)
    
    if [(-100 <= i <= 100) for i in arr] and (0 < len(arr) <= 100):
        positive_values = [i for i in arr if i > 0]
        number_positive_values = len(positive_values)
        postive_ratio = number_positive_values / n
        postive_ratio = '{:.6f}'.format(postive_ratio)
        
        negative_values = [i for i in arr if i < 0]
        number_negative_values = len(negative_values)
        negative_ratio = number_negative_values / n
        negative_ratio = '\n{:.6f}'.format(negative_ratio)
        
        zero_values = [i for i in arr if i == 0]
        number_zero_values = len(zero_values)
        zero_ratio = number_zero_values / n
        zero_ratio = '\n{:.6f}'.format(zero_ratio)
    else:
        raise ValueError('The size of the array is outside the the range 0 < n <= 100')
        
    print(postive_ratio, negative_ratio, zero_ratio)

In [3]:
arr = np.array(np.random.normal(0, 1, 100))

In [4]:
plusMinus(arr)

0.450000 
0.550000 
0.000000


# Question 2

In [5]:
def miniMaxSum(arr):
    # Write your code here
    if [(1 <= i <= 10**9) for i in arr]:
        sum_ = []
        if arr.count(arr[0]) == len(arr):
            print( 4*len(arr), 4*len(arr) )
        else:
            for i in range(len(arr)):
                sum_.append(sum([val for val in arr if not arr[i] == val]))
            min_value = min(sum_)
            max_value = max(sum_)
            print(min_value, max_value)
    else:
        raise ValueError('An array value is off the constraint--> 1 <= arr[i] <= 10^9')

In [6]:
miniMaxSum([1,2,3,4,5])

10 14


In [7]:
a = [5,5,5,5,5]

# Question 3

In [8]:
def timeConversion(s):
    # Write your code here
    hour = int(s[:2])
    
    if (hour == 12) and s.endswith('AM'):
        hour  = '00'
        return (hour + s[2:8])
    
    elif (hour != 12) and s.endswith('AM') :
        hour = s[:2]
        return (hour + s[2:8])

    elif (hour != 12) and s.endswith('PM'):
        hour = str(int(s[:2]) + 12)
        return (hour + s[2:8])
    
    elif (hour == 12) and s.endswith('PM'):
        hour = s[:2]
        return (hour + s[2:8])

In [9]:
s = '12:01:00PM'

s2 = '12:05:45PM'

In [10]:
timeConversion(s2)

'12:05:45'

In [11]:
def fizzBuzz(n):
    # Write your code here
    for i in range(1, n+1):
        if i % 3 == 0 and i % 5 == 0:
            print('FizzBuzz')
        elif i % 3 ==0 and i%5 != 0:
            print('Fizz')
        elif i % 5 ==0 and i%3 != 0:
            print('Buzz')
        elif i % 3 != 0 or i%5 != 0:
            print(i)

In [12]:
fizzBuzz(10)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz


In [7]:
def findMedian(arr):
    # Write your code here
    n = len(arr)
    arr = sorted(arr)
    median =  arr[n//2]
    return median

In [14]:
arr = [0, 3, 4, 1, 5]
findMedian(arr)

3

In [15]:
n_num = [1, 2, 3, 4, 5]
n = len(n_num)
n_num.sort()
  
if n % 2 == 0:
    median1 = n_num[n//2]
    median2 = n_num[n//2 - 1]
    median = (median1 + median2)/2
else:
    median = n_num[n//2]
print("Median is: " + str(median))

Median is: 3


In [16]:
 arr.count(arr[0]) == len(arr)

False

In [17]:
def lonelyinteger(a):
    # Write your code here
    n = len(a)
    if (1 <= n < 100) and n % 2 != 0:
        unique_element = [a[i] for i in range(len(a)) if a.count(a[i]) < 2][0]
        return unique_element
    else:
        raise ValueError('Length of array must be odd and one unique element')

In [18]:
matrix = np.array([ [1, 2, 3],
           [4, 5, 6],
           [9, 8, 9] ])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 9]])

In [19]:
def diagonalDifference(arr):
    # Write your code here
    dim = len(arr)
    right_diag = [arr[i][i] for i in range(dim)]
    left_diag = [arr[i][-(i+1)] for i in range(dim)]

    return abs(sum(right_diag) - sum(left_diag))

In [20]:
diagonalDifference(matrix)

2

In [22]:
arr4 = [1, 1, 3, 2, 1]

In [29]:
np.zeros(len(set(arr)), dtype = 'int')

array([0, 0, 0, 0, 0])

In [37]:
arr

[0, 3, 4, 1, 5]

In [54]:
def countingSort(arr):
    # Write your code here
    results = [0 for _ in range(100)]
    for i in range(len(arr)):
        results[arr[i]] += 1 
    return results

In [56]:
sorting = countingSort(arr)
sorting[:10]

[1, 1, 0, 1, 1, 1, 0, 0, 0, 0]

In [97]:
def ReverseMatrix(arr):
    col_2 = [arr[i][2] for i in range(len(arr))]
    col_2 = [col_2[len(col_2)-i] for i in range(1, len(col_2) + 1) ]
    
    for i in range(len(arr)):
        arr[i][2] = col_2[i]
        
    row_0 = arr[0]
    row_0 = [row_0[len(row_0)-i] for i in range(1, len(row_0) + 1) ]
    
    for i in range(len(arr)):
        arr[0][i] = row_0[i]
        
    return sum(arr[0][:2]) + sum(arr[1][:2])

In [108]:
matrix = [[112, 42, 83, 119], [56, 125, 56, 49], \
[15, 78, 101, 43], [62, 98, 114, 108]]

In [109]:
np.array(matrix)

array([[112,  42,  83, 119],
       [ 56, 125,  56,  49],
       [ 15,  78, 101,  43],
       [ 62,  98, 114, 108]])

In [110]:
ReverseMatrix(matrix)

414

In [111]:
np.array(matrix)

array([[119, 114,  42, 112],
       [ 56, 125, 101,  49],
       [ 15,  78,  56,  43],
       [ 62,  98,  83, 108]])

In [47]:
def pearson_coefficient(pys_score, his_score):
    
    mean_pys_score = sum(pys_score) / len(pys_score)
    mean_his_score = sum(his_score) / len(his_score)

    pys_mean_dev_sum = [(x - mean_pys_score) for x in pys_score]
    
    his_mean_dev_sum = [(y - mean_his_score) for y in his_score]
    
    numerator = sum( [( x*y ) for x, y in zip(pys_mean_dev_sum, his_mean_dev_sum) ])
    

    pys_mean_dev_sum_squared = [(x - mean_pys_score)**2 for x in pys_score]
    his_mean_dev_sum_squared = [(y - mean_his_score)**2 for y in his_score]
    
    denominator = sum(pys_mean_dev_sum_squared) * sum(his_mean_dev_sum_squared)

    pearson_coefficient = (numerator) / (denominator) ** 0.5
    print(round(pearson_coefficient, 3))

In [48]:
pys_score = [15,  12 , 8,   8,  7,   7,   7,   6,   5,   3]
his_score = [10,  25,  17,  11,  13,  17,  20,  13,  9,   15]

Score1 = [15,12,8,8,7,7,7,6,5,3] 
Score2 = [10,25,17,11,13,17,20,13,9,15]

pearson_coefficient(pys_score, his_score)

0.145


# Linear regression

In [ ]:
import numpy as np
from sklearn import linear_model as lm

F, N = map(int, input().split())
train_vals = np.array([input().split() for _ in range(N)], float)
T = int(input())
test = np.array([input().split() for _ in range(T)], float)

linReg = lm.LinearRegression()
linReg.fit(train_vals[:, :-1], train_vals[:, -1])
yhat = linReg.predict(test)
print(*yhat, sep='\n')

In [11]:
import numpy as np
data = [1,1, 1, 2,3, 5, 5, 8, 12, 13, 14, 14, 15, 15, 18, 100]
first_quartile, second, third = np.quantile(data, 0.25), np.quantile(data, 0.5), np.quantile(data, 0.75)

In [12]:
first_quartile, second, third

(2.75, 10.0, 14.25)

In [8]:
list_ = [7, 1, 9, 13, 10]


findMedian(list_)

9

In [9]:
np.mean(np.array(list_))

8.0

In [10]:
np.std(np.array(list_))

4.0

In [ ]:
total_sum = 0
for i in range(i, j):
    total_sum+=i

for j in range(j, k-1, -1):
    total_sum+=j

PhD interview preparations

In [8]:
def is_palindrome(s):
    return all(s[i] == s[-i-1] for i in range(len(s)//2))

# or 
def is_palindrome_alt(s):
    return s == s[::-1]

In [9]:
is_palindrome([2, 5, 7, 4, 5]), is_palindrome_alt([2, 5, 7, 4, 5])

(False, False)

In [22]:
def is_anagram(a, b):
    try:
        assert len(a) == len(b)
    except AssertionError:
        raise(AssertionError('Both string must have same length'))
    if (len(set(a)) == len(a)) and (len(set(b)) == len(b)):
        return all(c in b for c in a) and all(c in a for c in b)
    return False

In [25]:
is_anagram('1233', '4123')

False

In [3]:
def fibonacci(n):
    fib_nums = [1,1]
    for _ in range(2,n+1):
        fib_nums.append(fib_nums[-1]+fib_nums[-2])
    return fib_nums[-1]

In [4]:
fibonacci(15)

987

In [40]:
# counts the number of times a charachter appears in a given list
def repeated_chars(some_list):
    unique_chars = set(some_list)
    repeat_nums = {}
    for char in unique_chars:
        count = sum(val == char for val in some_list)
        repeat_nums[str(char)] = count

    return repeat_nums
repeated_chars([1, 3, 6, 9, 2, 4, 1, 4, 4, 5, 3, 5])

In [1]:
prices = [7,1,5,3,6,4]

prices.index(7)

0

In [10]:
class Solution:
    def maxProfit(self, prices):
        buy_amount = min(prices)
        print(f"Buying stock at price {buy_amount}")
        prosp_prices = prices[prices.index(buy_amount):]
        sell_amount = max(prosp_prices)
        print(f"Selling stock at price {sell_amount}")
        return f"Profit made at sale: {sell_amount - buy_amount}"

best_buy = Solution()
print(best_buy.maxProfit(prices))
print(best_buy.maxProfit([1, 3, 6, 9, 2, 4, 1, 4, 4, 5, 3, 5]))

Buying stock at price 1
Selling stock at price 6
Profit made at sale: 5
Buying stock at price 1
Selling stock at price 9
Profit made at sale: 8


In [9]:
best_buy.maxProfit([7,6,4,3,1])

Buying stock at price 1
Selling stock at price 1


'Profit made at sale: 0'

In [23]:
prices

[7, 1, 5, 3, 6, 4]

In [29]:
class Solution2:
    def maxProfit(self, prices):
        profit = 0
        for _ in range(len(prices)):
            buy_amount = min(prices)
            print(f"buy at {buy_amount}")
            price_trend = prices[prices.index(buy_amount)+1:]
            if (len(prices) > 2) and (buy_amount <  price_trend[0]):
                profit += (price_trend[0] - buy_amount)
                print(f"made profit {profit}")
                prices = price_trend
            else:
                return profit
        

best_buy2 = Solution2()
print(best_buy2.maxProfit(prices))

buy at 1
made profit 4
buy at 3
made profit 7
buy at 4
7


In [52]:
# Probability of getting a sum of 4 for two equally weighted dice
import numpy as np
rol = list(range(1, 7))
matrix_pairs = np.zeros(36).reshape(6,6)

count = 0
for i in range(len(rol)):
    for j in range(len(rol)):
        sum = rol[i] + rol[j]
        matrix_pairs[i, j] = sum
        if sum == 4:
            count +=1
print(f"Probability of sum of two is: {count/36:.4f}")
matrix_pairs

Probability of sum of two is: 0.0833


array([[ 2.,  3.,  4.,  5.,  6.,  7.],
       [ 3.,  4.,  5.,  6.,  7.,  8.],
       [ 4.,  5.,  6.,  7.,  8.,  9.],
       [ 5.,  6.,  7.,  8.,  9., 10.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [ 7.,  8.,  9., 10., 11., 12.]])

In [54]:
matrix_pairs

array([[ 2.,  3.,  4.,  5.,  6.,  7.],
       [ 3.,  4.,  5.,  6.,  7.,  8.],
       [ 4.,  5.,  6.,  7.,  8.,  9.],
       [ 5.,  6.,  7.,  8.,  9., 10.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [ 7.,  8.,  9., 10., 11., 12.]])